server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${user.home}/config-repo
  security:
    user:
      name: root
      password: s3cr3t

logging:
  level:
    org.springframework.cloud: 'DEBUG'
