spring:
  cloud:
    config:
      server:
        git:
          uri: ${user.home}/config-repo
  security:
    user:
      name: ${FEDER8_CONFIG_SERVER_USERNAME:root}
      password: ${FEDER8_CONFIG_SERVER_PASSWORD:s3cr3t}
