---
feder8:
  local:
    host:
      name: ""
      portal-url: "http://${feder8.local.host.name}"
      token-url: "http://local-portal:8080/portal/api/token"
      atlas-url: "${feder8.local.host.portal-url}/atlas/"
      atlas-container-url: "http://atlas:8080"
      zeppelin-url: "${feder8.local.host.portal-url}/zeppelin/"
      zeppelin-container-url: "http://zeppelin:8080/zeppelin/"
      user-mgmt-url: "${feder8.local.host.portal-url}/user-mgmt"
      user-mgmt-container-url: "http://user-mgmt:8080/user-mgmt"
      feder8-studio-url: ""
      feder8-studio-container-url: ""
      vscode-url: "${feder8.local.host.feder8-studio-url}/app/vscode"
      rstudio-url: "${feder8.local.host.feder8-studio-url}/app/rstudio"
      apps-reports-url: "${feder8.local.host.feder8-studio-url}/app/reports"
      documents-url: "${feder8.local.host.feder8-studio-url}/app/documents"
      personal-url: "${feder8.local.host.feder8-studio-url}/app/personal"
      task-manager-url: "${feder8.local.host.portal-url}/task-manager"
      task-manager-container-url: "http://task-manager:8080/task-manager"
      data-directory: ""
      feder8-studio-directory: ""
      zeppelin-notebook-directory: ""
      zeppelin-log-directory: ""
      docker-cert-directory: ""
    datasource:
      dbms: "postgresql"
      host: ""
      name: ""
      port: ""
      username: ""
      password: ""
      admin-username: ""
      admin-password: ""
      cdm-schema: "omopcdm"
      vocabulary-schema: "omopcdm"
      results-schema: "results"
      scratch-schema: "scratch"
    security:
      security-method: ""
      ldap-url: ""
      ldap-base-dn: ""
      ldap-dn: ""
      ldap-system-username: ""
      ldap-system-password: ""
      user-mgmt-username: ""
      user-mgmt-password: ""
  central:
    service:
      oauth-issuer-uri: ""
      oauth-token-uri: "${feder8.central.service.oauth-issuer-uri}/token"
      oauth-user-info-uri: "${feder8.central.service.oauth-issuer-uri}/profile"
      oauth-client-id: ""
      oauth-client-secret: ""
      oauth-username: ""
      oauth-refresh-token: ""
      image-repo: ""
      image-repo-username: ""
      image-repo-key: ""
      catalogue-base-uri: ""
      catalogue-api-url: "${feder8.central.service.catalogue-base-uri}/api"
      distributed-analytics-base-uri: ""
      distributed-analytics-api-url: "${feder8.central.service.distributed-analytics-base-uri}/api"